

  // Patterns generated by consulting the following URLs:
  //
  //  - http://en.wikipedia.org/wiki/VAT_identification_number
  //  - http://ec.europa.eu/taxation_customs/vies/faq.html
  //  - http://www.skatteetaten.no/en/International-pages/Felles-innhold-benyttes-i-flere-malgrupper/Brochure/Guide-to-value-added-tax-in-Norway/?chapter=7159
  ID_PATTERNS = {
      AT: { // Austria
          regex: /^U\d{8}$/,
          code: 'AT'
      },
      BE: { // Belgium
          regex: /^(1|0?)\d{9}$/,
          code: 'BE'
      },
      BG: { // Bulgaria
          regex: /^\d{9,10}$/,
          code: 'BG'
      },
      CY: { // Cyprus
          regex: /^\d{8}[A-Z]$/,
          code: 'CY'
      },
      CZ: { // Czech Republic
          regex: /^\d{8,10}$/,
          code: 'CZ'
      },
      DE: { // Germany
          regex: /^\d{9}$/,
          code: 'DE'
      },
      DK: { // Denmark
          regex: /^\d{8}$/,
          code: 'DK'
      },
      EE: { // Estonia
          regex: /^\d{9}$/,
          code: 'EE'
      },
      EL: { // Greece
          regex: /^\d{9}$/,
          code: 'GR'
      },
      ES: { // Spain
          regex: /^[A-Z0-9]\d{7}[A-Z0-9]$/,
          code: 'ES'
      },
      FI: { // Finland
          regex: /^\d{8}$/,
          code: 'FI'
      },
      FR: { // France
          regex: /^[A-Z0-9]{2}\d{9}$/,
          code: 'FR'
      },
      GB: { // United Kingdom
          regex: /^(GD\d{3}|HA\d{3}|\d{9}|\d{12})$/,
          code: 'GB'
      },
      HR: { // Croatia
          regex: /^\d{11}$/,
          code: 'HR'
      },
      HU: { // Hungary
          regex: /^\d{8}$/,
          code: 'HU'
      },
      IE: { // Ireland
          regex: /^(\d{7}[A-Z]{1,2}|\d[A-Z+*]\d{5}[A-Z])$/,
          code: 'IE'
      },
      IT: { // Italy
          regex: /^\d{11}$/,
          code: 'IT'
      },
      LT: { // Lithuania
          regex: /^(\d{9}|\d{12})$/,
          code: 'LT'
      },
      LU: { // Luxembourg
          regex: /^\d{8}$/,
          code: 'LU'
      },
      LV: { // Latvia
          regex: /^\d{11}$/,
          code: 'LV'
      },
      MT: { // Malta
          regex: /^\d{8}$/,
          code: 'MT'
      },
      NL: { // Netherlands
          regex: /^\d{9}B\d{2}$/,
          code: 'NL'
      },
      NO: { // Norway
          regex: /^\d{9}MVA$/,
          code: 'NO'
      },
      PL: { // Poland
          regex: /^\d{10}$/,
          code: 'PL'
      },
      PT: { // Portugal
          regex: /^\d{9}$/,
          code: 'PT'
      },
      RO: { // Romania
          regex: /^\d{2,10}$/,
          code: 'RO'
      },
      SE: { // Sweden
          regex: /^\d{12}$/,
          code: 'SE'
      },
      SI: { // Slovenia
          regex: /^\d{8}$/,
          code: 'SI'
      },
      SK: { // Slovakia
          regex: /^\d{10}$/,
          code: 'SK'
      },
  };
